api/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("v1/peliculas/", views.PeliculaList.as_view(),name="peli_list"),
    path("v1/peliculas/<str:codigo>", views.PelicualDetalle.as_view(),name="peli_det"),
]

app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('bases.urls', 'bases'), namespace='bases')),
    path('inv/', include(('inv.urls', 'inv'), namespace='inv')),
    path('cmp/', include(('cmp.urls', 'cmp'), namespace='cmp')),
    path('fac/', include(('fac.urls', 'fac'), namespace='fac')),
    path('api/', include(('api.urls', 'api'), namespace='api')),

    path('admin/', admin.site.urls),
]

bases/urls.py
from django.urls import path
from django.contrib.auth import views as av

from . import views

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('login/', av.LoginView.as_view(template_name='bases/login.html'), name='login'),
    path('logout/', av.LogoutView.as_view(template_name='bases/login.html'), name='logout'),
    path('sin_privilegios/', views.HomeSimp.as_view(), name='simp'),
]

templates/base/simp.html
{% extends 'base/base.html' %}


{% block content %}
    
    <div class="col-xl-6 col-md-6 mb-6">
        <div class="card border-left-danger shadow h-100 py-2">
        <div class="card-body">
            <div class="row no-gutters align-items-center">
            <div class="col mr2">
                <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                    Usuario: <mark>{{ user.username }} {{user.get_full_name}}</mark>
                </div>
                <div class="dropdwon-divider"></div>

                <div class="row">
                    <mark>No tiene suficientes privilegios</mark> para cargar la opción solicitada.
                    <br>
                    <small>Para poder acceder debes loguearte con un usuario con privilegios necesarios</small>
                </div>
                <div class="dropdwon-divider"></div>
                <div class="row">
                    <div class="col">
                        <a href="{% url 'bases:home' %}" class="btn btn-success"><span class="fa fa-home"></span> Ir a inicio</a>
                        <a href="{% url 'bases:login' %}" class="btn btn-success"><span class="fa fa-user"></span> Ingresar con otro usuario</a>
                    </div>
                </div>

            </div>
            <div class="col-auto">
                <i class="far fa-calendar-plus fa-2x text-gray-300"></i>
            </div>
            </div>
        </div>
        </div>
    </div>

{% endblock content %}
    