api/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("v1/peliculas/", views.PeliculaList.as_view(),name="peli_list"),
    path("v1/peliculas/<str:codigo>", views.PelicualDetalle.as_view(),name="peli_det"),
]

app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('bases.urls', 'bases'), namespace='bases')),
    path('inv/', include(('inv.urls', 'inv'), namespace='inv')),
    path('cmp/', include(('cmp.urls', 'cmp'), namespace='cmp')),
    path('fac/', include(('fac.urls', 'fac'), namespace='fac')),
    path('api/', include(('api.urls', 'api'), namespace='api')),

    path('admin/', admin.site.urls),
]

inv/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('categorias/', views.CategoriaView.as_view(), name='categoria_list'),
    path('categorias/new', views.CategoriaNew.as_view(), name='categoria_new'),
    path('categorias/edit/<int:pk>', views.CategoriaEdit.as_view(), name='categoria_edit'),
    path('categorias/del/<int:pk>', views.CategoriaDel.as_view(), name='categoria_del'),

    path('subcategorias/', views.SubCategoriaView.as_view(), name='subcategoria_list'),
    path('subcategorias/new', views.SubCategoriaNew.as_view(), name='subcategoria_new'),
    path('subcategorias/edit/<int:pk>', views.SubCategoriaEdit.as_view(), name='subcategoria_edit'),
    path('subcategorias/del/<int:pk>', views.SubCategoriaDel.as_view(), name='subcategoria_del'),

    path('productoras/', views.ProductoraView.as_view(), name='productora_list'),
    path('productoras/new', views.ProductoraNew.as_view(), name='productora_new'),
    path('productoras/edit/<int:pk>', views.ProductoraEdit.as_view(), name='productora_edit'),
    path('productoras/inactivar/<int:id>', views.productora_inactivar, name='productora_inactivar'),

    path('peliculas/', views.PeliculaView.as_view(), name='pelicula_list'),
    path('peliculas/new', views.PeliculaNew.as_view(), name='pelicula_new'),
    path('peliculas/edit/<int:pk>', views.PeliculaEdit.as_view(), name='pelicula_edit'),
    path('peliculas/inactivar/<int:id>', views.pelicula_inactivar, name='pelicula_inactivar'),


]

bases/models.py
from django.db import models
from django_userforeignkey.models.fields import UserForeignKey


from django.contrib.auth.models import User
# Create your models here.


class ClaseModelo(models.Model):


    estado = models.BooleanField(default=True)
    fc = models.DateTimeField('Fecha creado', auto_now_add=True)
    fm = models.DateTimeField('fecha modificado', auto_now=True, auto_now_add=False)
    uc = models.ForeignKey(User, on_delete=models.CASCADE)
    um = models.PositiveIntegerField(null=True, blank=True)


    class Meta:
        abstract = True



class ClaseModelo2(models.Model):


    estado = models.BooleanField(default=True)
    fc = models.DateTimeField('Fecha creado', auto_now_add=True)
    fm = models.DateTimeField('fecha modificado', auto_now=True, auto_now_add=False)
    # uc = models.ForeignKey(User, on_delete=models.CASCADE)
    # um = models.PositiveIntegerField(null=True, blank=True)
    uc = UserForeignKey(auto_user_add=True, related_name='+')
    um = UserForeignKey(auto_user=True, related_name='+')


    class Meta:
        abstract = True

inv/models.py
from django.db import models

from bases.models import ClaseModelo



class Categoria(ClaseModelo):

    descripcion = models.CharField('Descripción de la categoría', max_length=100, unique=True)

    
    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Categoria, self).save()

    class Meta:
        verbose_name_plural = 'Categorias'
        


class SubCategoria(ClaseModelo):

    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    descripcion = models.CharField('Descripción de la categoría', max_length=100)


    def __str__(self):
        return '{}-{}'.format(self.categoria.descripcion, self.descripcion)


    def save(self):
        self.descripcion = self.descripcion.upper()
        super(SubCategoria, self).save()

    class Meta:
        verbose_name_plural = 'Sub Categorias'
        unique_together = ('categoria', 'descripcion')


class Productora(ClaseModelo):

    nombre = models.CharField('Empresa productora', max_length=100, unique=True)


    def __str__(self):
        return '{}'.format(self.nombre)


    def save(self):
        self.nombre = self.nombre.upper()
        super(Productora, self).save()

    class Meta:
        verbose_name_plural = 'Productoras'


class Pelicula(ClaseModelo):

    codigo = models.CharField('Código de pelicula', max_length=50, unique=True)
    nombre = models.CharField('Nombre de la película', max_length=80)
    description = models.CharField('descripción', max_length=500)
    precio = models.FloatField(default=0)
    existencia = models.PositiveIntegerField(default=1)
    last_buy = models.DateField('Última compra', null=True, blank=True)

    productora = models.ForeignKey(Productora, on_delete=models.CASCADE)
    subcategoria = models.ForeignKey(SubCategoria, on_delete=models.CASCADE)

    def __str__(self):

        return self.nombre

    def save(self):
        self.nombre = self.nombre.upper()
        super(Pelicula, self).save()


    class Meta:
        verbose_name_plural = 'Películas'
        unique_together = ('codigo', )

inv/forms.py
from django import forms
from django.forms import widgets


from .models import Categoria, SubCategoria, Productora, Pelicula


class CategoriaForm(forms.ModelForm):

    class Meta:
        model = Categoria
        fields = ['descripcion', 'estado']
        labels = {'descripcion': 'Descripción de la Categoría',
                 'estado': 'Estado'}
        widget = {'descripcion': forms.TextInput}

    
    def __init__(self, *args, **kwargs):
        super(CategoriaForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })


class SubCategoriaForm(forms.ModelForm):

    categoria = forms.ModelChoiceField(
        queryset=Categoria.objects.filter(estado=True).order_by('descripcion')
    )

    class Meta:
        model = SubCategoria
        fields = ['categoria', 'descripcion', 'estado']
        labels = {'descripcion': 'Sub Categoría',
                 'estado': 'Estado'}
        widget = {'descripcion': forms.TextInput}

    
    def __init__(self, *args, **kwargs):
        super(SubCategoriaForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

        self.fields['categoria'].empty_label = "Seleccione Categoria"


class ProductoraForm(forms.ModelForm):

    class Meta:
        model = Productora
        fields = ['nombre', 'estado']
        labels = {'estado': 'Estado'}
        widget = {'nombre': forms.TextInput}

    
    def __init__(self, *args, **kwargs):
        super(ProductoraForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

class PeliculaForm(forms.ModelForm):

    class Meta:
        model = Pelicula
        fields = ['codigo','nombre', 'estado', 'description', 'precio', 'existencia', 'last_buy', 'productora', 'subcategoria']
        exclude = ['um', 'fm', 'uc', 'fc']
        widget = {'nombre': forms.TextInput}

    
    def __init__(self, *args, **kwargs):
        super(PeliculaForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })
        self.fields['last_buy'].widget.attrs['readonly'] = True
        self.fields['existencia'].widget.attrs['readonly'] = True

inv/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin

from django.contrib import messages
from django.views import generic

from django.contrib.auth.decorators import login_required, permission_required

from bases.views import Simp
# Create your views here.

from .models import Categoria, SubCategoria, Productora, Pelicula
from .forms import CategoriaForm, SubCategoriaForm, ProductoraForm, PeliculaForm

class CategoriaView(Simp, generic.ListView):

    model = Categoria
    template_name = 'inv/categoria_list.html'
    context_object_name = 'obj'
    permission_required = 'inv.view_categoria'


class CategoriaNew(SuccessMessageMixin, Simp, generic.CreateView):

    model = Categoria
    template_name = 'inv/categoria_form.html'
    context_object_name = 'obj'
    form_class = CategoriaForm
    success_url = reverse_lazy('inv:categoria_list')
    success_message = "Categoria creada satisfactoriamente"
    permission_required = 'inv.add_categoria'


    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)




class CategoriaEdit(SuccessMessageMixin, Simp, generic.UpdateView):

    model = Categoria
    template_name = 'inv/categoria_form.html'
    context_object_name = 'obj'
    form_class = CategoriaForm
    success_url = reverse_lazy('inv:categoria_list')
    success_message = "Categoria actualizada satisfactoriamente"
    permission_required = 'inv.change_categoria'


    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)


class CategoriaDel(Simp, generic.DeleteView):

    model = Categoria
    template_name = 'inv/catalogos_del.html'
    context_object_name = 'obj'
    success_url = reverse_lazy('inv:categoria_list')
    permission_required = 'inv.delete_categoria'


class SubCategoriaView(Simp, generic.ListView):

    model = SubCategoria
    template_name = 'inv/subcategoria_list.html'
    context_object_name = 'obj'
    permission_required = 'inv.view_subcategoria'





class SubCategoriaNew(Simp, generic.CreateView):

    

    model = SubCategoria
    template_name = 'inv/subcategoria_form.html'
    context_object_name = 'obj'
    form_class = SubCategoriaForm
    success_url = reverse_lazy('inv:subcategoria_list')
    permission_required = 'inv.add_subcategoria'


    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)



class SubCategoriaEdit(Simp, generic.UpdateView):

    model = SubCategoria
    template_name = 'inv/subcategoria_form.html'
    context_object_name = 'obj'
    form_class =SubCategoriaForm
    success_url = reverse_lazy('inv:subcategoria_list')
    permission_required = 'inv.change_subcategoria'


    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)




class SubCategoriaDel(Simp, generic.DeleteView):

    model = SubCategoria
    template_name = 'inv/catalogos_del.html'
    context_object_name = 'obj'
    success_url = reverse_lazy('inv:subcategoria_list')
    permission_required = 'inv.delete_subcategoria'





class ProductoraView(Simp, generic.ListView):

    model = Productora
    template_name = 'inv/productora_list.html'
    context_object_name = 'obj'
    permission_required = 'inv.view_productora'




class ProductoraNew(Simp, generic.CreateView):

    

    model = Productora
    template_name = 'inv/productora_form.html'
    context_object_name = 'obj'
    form_class = ProductoraForm
    success_url = reverse_lazy('inv:productora_list')
    permission_required = 'inv.add_productora'


    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)



class ProductoraEdit(Simp, generic.UpdateView):

    model = Productora
    template_name = 'inv/productora_form.html'
    context_object_name = 'obj'
    form_class =ProductoraForm
    success_url = reverse_lazy('inv:productora_list')
    permission_required = 'inv.change_productora'


    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)

@login_required(login_url='/login/')
@permission_required('inv.change_productora', login_url='bases:simp')
def productora_inactivar(request, id):
    productora = Productora.objects.get(pk=id)
    contexto = {}

    if not productora:
        return redirect('inv:productora_list')

    if request.method == 'GET':
        contexto = {
            'obj': productora
        }

    if request.method == 'POST':
        productora.estado = False
        productora.save()
        messages.success(request, 'Productora Inactivada')
        return redirect('inv:productora_list')



    return render(request, 'inv/catalogos_del.html', contexto)

    



class PeliculaView(Simp, generic.ListView):

    model = Pelicula
    template_name = 'inv/pelicula_list.html'
    context_object_name = 'obj'
    permission_required = 'inv.view_pelicula'





class PeliculaNew(Simp, generic.CreateView):

    

    model = Pelicula
    template_name = 'inv/pelicula_form.html'
    context_object_name = 'obj'
    form_class = PeliculaForm
    success_url = reverse_lazy('inv:pelicula_list')
    permission_required = 'inv.add_pelicula'


    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)



class PeliculaEdit(Simp, generic.UpdateView):

    model = Pelicula
    template_name = 'inv/pelicula_form.html'
    context_object_name = 'obj'
    form_class =PeliculaForm
    success_url = reverse_lazy('inv:pelicula_list')
    permission_required = 'inv.change_pelicula'


    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)

@login_required(login_url='/login/')
@permission_required('inv.change_pelicula', login_url='bases:simp')
def pelicula_inactivar(request, id):
    pelicula = Pelicula.objects.get(pk=id)
    contexto = {}

    if not pelicula:
        return redirect('inv:pelicula_list')

    if request.method == 'GET':
        contexto = {
            'obj': pelicula
        }

    if request.method == 'POST':
        pelicula.estado = False
        pelicula.save()
       
        return redirect('inv:pelicula_list')



    return render(request, 'inv/catalogos_del.html', contexto)

    

templates/inv/catalogos_del.html
{% extends 'base/base.html' %}



{% block content %}
    
<form action="" method="post" class="form-inline">
    {% csrf_token %}
    <div class="col-xl-4 col-md-6 mb-4">
        <div class="card border-left-danger shadow h-100 py-2">
          <div class="card-body">
            <div class="row no-gutters align-items-center">
              <div class="col mr-2">
                <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">¿Eliminar {% if obj.descripcion %} "{{ obj.descripcion }}" {% endif %} {% if obj.categoria%} de la categoria "{{ obj.categoria }}" {% endif %}
                    {% if obj.nombre %} {{ obj.nombre }} {% endif %}?</div>
                <button type="submit" class="btn btn-danger">Sí, eliminar</button>
                <!-- <a href="{% url 'inv:categoria_list' %}" class="btn btn-warning"><span class="fa fa-undo"></span> Cancelar</a> -->
                <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-warning"><span class="fa fa-undo"></span> Cancelar</a>
            </div>
              <div class="col-auto">
                <i class="far fa-question-circle fa-2x text-gray-300"></i>
              </div>
            </div>
          </div>
        </div>
      </div>
</form>

{% endblock content %}
    


{% block js %}
    
{% endblock js %}
    

templates/inv/categoria_form.html
{% extends 'base/base.html' %}



{% block content %}
    
<form action="" method="post" class="form-inline">
    {% csrf_token %}
    <div class="col-xl-6 col-md-6 mb-6">
        
        {% if obj %}
        <div class="card border-left-warning shadow h-100 py-2">
        {% else %}
        <div class="card border-left-success shadow h-100 py-2">

        {% endif %}
            
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                          
                          {% if obj %}
                              Editar
                            {% else %}
                            Nueva
                          {% endif %}
                             Categoria
                        </div>
                        <div class="dropdwon-divider"></div>
                        <div class="row my-3">
                            <div class="col-10">
                                <div class="input-group">
                                    <input type="text" name="descripcion" id="id_descripcion" maxlength="100" required placeholder="Descripción" value="{% if obj %}{{ obj.descripcion }}{% endif %}" class="form-control">
                                </div>
                            </div>
                            <div class="col-2">
                                <div class="form-group">
                                    <label for="id_estado">Estado</label>
                                    <input type="checkbox" name="estado" id="id_estado" 
                                    
                                    {% if obj.estado %}
                                        checked    
                                    {% endif %}
                                     class="form-control">
                                </div>
                            </div>
                        </div>
                        <div class="dropdwon-divider"></div>
                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-success"><span class="fa fa-save"></span> Guardar</button>
                                <a href="{% url 'inv:categoria_list' %}" class="btn btn-danger"><span class="fa fa-undo"></span> Cancelar</a>
                            </div>
                        </div>
                    </div>
    
                </div>
            </div>
        </div>
    </div>
</form>

{% endblock content %}
    


{% block js %}
    
{% endblock js %}
    

templates/inv/categoria_list.html
{% extends 'base/base.html' %}



{% block content %}
    
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Listado de Categorías</h6>
      <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
          <div class="dropdown-header">Acciones</div>
          <a class="dropdown-item" href="{% url 'inv:categoria_new' %}"><i class="far fa-calendar-plus"></i> Nueva</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
     
     {% if not obj %}
         <div class="alert alert-info">No hay Categorias</div>
     {% else %}
     <table class="table table-striper table-hover">
         <thead>
             <th>Id</th>
             <th>Descripción</th>
             <th>Estado</th>
             <th>Fecha Creado</th>
             <th>Fecha Modificado</th>
             <th class="all">Acciones</th>
         </thead>
         <tbody>
             
             {% for item in obj %}
                 <tr>
                     <td>{{ item.id }}</td>
                     <td>{{ item.descripcion }}</td>
                     <td>{{ item.estado|yesno:"Activo,Inactivo" }}</td>
                     <td>{{ item.fc|date:"d/m/Y" }}</td>
                     <td>{{ item.fm }}</td>
                     <td>
                         <a href="{% url 'inv:categoria_edit' item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
                         <a href="{% url 'inv:categoria_del' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
                     </td>
                 </tr>
             {% endfor %}
                 
         </tbody>
     </table>
     {% endif %}
    </div>
  </div>

{% endblock content %}
    


{% block js %}
    

<script>
    $(document).ready(function(){
        $('.table').DataTable();
    });
</script>


{% endblock js %}
    

templates/inv/pelicula_form.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">


        
        {% if obj %}
        <form action="{% url 'inv:pelicula_edit' obj.pk %}" role="form" method="post" class="form-inline">
        
        {% else %}
        <form action="{% url 'inv:pelicula_new' %}" role="form" method="post" class="form-inline">

        {% endif %}
            
            {% csrf_token %}
            <div class="col-xl-12 col-md-12 mb-12">
                
                {% if obj %}
                <div class="card border-left-warning shadow h-100 py-2">
                {% else %}
                <div class="card border-left-success shadow h-100 py-2">

                {% endif %}
                    
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                
                                {% if obj %}
                                    Editar
                                    {% else %}
                                    Nueva
                                {% endif %}
                                    Película
                                </div>
                                <div class="dropdwon-divider"></div>
                                <div class="row my-3">
                                    {{ form.as_p }}
                                </div>
                                <div class="dropdwon-divider"></div>
                                <div class="row">
                                    <div class="col">
                                        <button type="submit" class="btn btn-success"><span class="fa fa-save"></span> Guardar</button>
                                        <!-- <a href="{% url 'inv:pelicula_list' %}" class="btn btn-danger"><span class="fa fa-undo"></span> Cancelar</a> -->
                                        <button class="btn btn-danger" onclick="return cerrar_modal()">Cancelar</button>
                                    </div>
                                </div>
                            </div>
            
                        </div>
                    </div>
                </div>
            </div>
        </form>

    </div>
</div>  
    

templates/inv/pelicula_list.html
{% extends 'base/base.html' %}



{% block content %}
    
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Listado de Películas</h6>
      <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
          <div class="dropdown-header">Acciones</div>
          <a class="dropdown-item" href="#" onclick="return abrir_modal('{% url 'inv:pelicula_new' %}')"><i class="far fa-calendar-plus"></i> Nueva</a>
          
        </div>
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
     
     {% if not obj %}
         <div class="alert alert-info">No hay películas que mostrar</div>
     {% else %}
     <table class="table table-striper table-hover">
         <thead>
             <th>Id</th>
             <th>Nombre de la película</th>
           
             <th>Existencia</th>
             <th>Productora</th>
             <th>Género</th>
             <th class="all">Acciones</th>
         </thead>
         <tbody>
             
             {% for item in obj %}
                 <tr>
                     <td>{{ item.id }}</td>
                     <td>{{ item.nombre }}</td>
                     
                     <td>{{ item.existencia }}</td>
                     <td>{{ item.productora }}</td>
                     <td>{{ item.subcategoria }}</td>
                     <td>
                         <a href="#" onclick="return abrir_modal('{% url 'inv:pelicula_edit' item.id %}')" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
                         <a href="{% url 'inv:pelicula_inactivar' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-thumbs-down"></i></a>
                     </td>
                 </tr>
             {% endfor %}
                 
         </tbody>
     </table>
     {% endif %}
    </div>
  </div>

{% endblock content %}
    


{% block js %}
    

<script>
    $(document).ready(function(){
        $('.table').DataTable();
    });
</script>


{% endblock js %}
    

templates/inv/productora_list.html
{% extends 'base/base.html' %}



{% block content %}
    
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Listado de Productoras</h6>
      <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
          <div class="dropdown-header">Acciones</div>
          <a class="dropdown-item" href="{% url 'inv:productora_new' %}"><i class="far fa-calendar-plus"></i> Nueva</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
     
     {% if not obj %}
         <div class="alert alert-info">No hay Productoras que mostrar</div>
     {% else %}
     <table class="table table-striper table-hover">
         <thead>
             <th>Id</th>
             <th>Nombre de la productora</th>
             <th>Estado</th>
             <th>Fecha Creado</th>
             <th>Fecha Modificado</th>
             <th class="all">Acciones</th>
         </thead>
         <tbody>
             
             {% for item in obj %}
                 <tr>
                     <td>{{ item.id }}</td>
                     <td>{{ item.nombre }}</td>
                     <td>{{ item.estado|yesno:"Activo,Inactivo" }}</td>
                     <td>{{ item.fc|date:"d/m/Y" }}</td>
                     <td>{{ item.fm }}</td>
                     <td>
                         <a href="{% url 'inv:productora_edit' item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
                         <a href="{% url 'inv:productora_inactivar' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-thumbs-down"></i></a>
                     </td>
                 </tr>
             {% endfor %}
                 
         </tbody>
     </table>
     {% endif %}
    </div>
  </div>

{% endblock content %}
    


{% block js %}
    

<script>
    $(document).ready(function(){
        $('.table').DataTable();
    });
</script>


{% endblock js %}
    

templates/inv/subcategoria_list.html
{% extends 'base/base.html' %}



{% block content %}
    
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Listado de Sub Categorías</h6>
      <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
          <div class="dropdown-header">Acciones</div>
          <a class="dropdown-item" href="{% url 'inv:subcategoria_new' %}"><i class="far fa-calendar-plus"></i> Nueva</a>
         
        </div>
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
     
     {% if not obj %}
         <div class="alert alert-info">No hay Sub Categorias</div>
     {% else %}
     <table class="table table-striper table-hover">
         <thead>
             <th>Categoría</th>
             <th>Id</th>
             <th>Descripción</th>
             <th>Estado</th>
             <th>Fecha Creado</th>
             <th>Fecha Modificado</th>
             <th class="all">Acciones</th>
         </thead>
         <tbody>
             
             {% for item in obj %}
                 <tr>
                     <td>{{ item.categoria }}</td>
                     <td>{{ item.id }}</td>
                     <td>{{ item.descripcion }}</td>
                     <td>{{ item.estado|yesno:"Activo,Inactivo" }}</td>
                     <td>{{ item.fc|date:"d/m/Y" }}</td>
                     <td>{{ item.fm }}</td>
                     <td>
                         <a href="{% url 'inv:subcategoria_edit' item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
                         <a href="{% url 'inv:subcategoria_del' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
                     </td>
                 </tr>
             {% endfor %}
                 
         </tbody>
     </table>
     {% endif %}
    </div>
  </div>

{% endblock content %}
    


{% block js %}
    

<script>
    $(document).ready(function(){
        $('.table').DataTable();
    });
</script>


{% endblock js %}
    