api/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("v1/peliculas/", views.PeliculaList.as_view(),name="peli_list"),
    path("v1/peliculas/<str:codigo>", views.PelicualDetalle.as_view(),name="peli_det"),
]

app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('bases.urls', 'bases'), namespace='bases')),
    path('inv/', include(('inv.urls', 'inv'), namespace='inv')),
    path('cmp/', include(('cmp.urls', 'cmp'), namespace='cmp')),
    path('fac/', include(('fac.urls', 'fac'), namespace='fac')),
    path('api/', include(('api.urls', 'api'), namespace='api')),

    path('admin/', admin.site.urls),
]

fac/urls.py
from django.urls import path

from . import views, reportes

urlpatterns = [
   
   path('clientes/', views.ClienteView.as_view(), name='cliente_list'),
   path('clientes/new', views.ClienteNew.as_view(), name='cliente_new'),
   path('clientes/<int:pk>', views.ClienteEdit.as_view(), name='cliente_edit'),
   path('cliente/estado/<int:id>', views.cliente_inactivar, name='cliente_inactivar'),


   path('facturas/', views.FacturaView.as_view(), name="factura_list"),
   path('facturas/new', views.facturas, name="factura_new"),
   path('facturas/edit/<int:id>', views.facturas, name="factura_edit"),


   path('facturas/buscar-producto', views.PeliculaView.as_view(), name="factura_peli"),
   path('facturas/borrar-detalle/<int:id>', views.borrar_detalle_factura, name="factura_borrar_det"),


   path('facturas/imprimir/<int:id>', reportes.factura_recibo_imprimir, name="factura_imprimir_one"),
   path('facturas/imprimir-todas/<str:f1>/<str:f2>', reportes.imprimir_factura_list, name="factura_imprimir_all"),
   
]

fac/models.py
from django.db import models

# Create your models here.


#Para los signals
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.db.models import Sum

from bases.models import ClaseModelo, ClaseModelo2
import fac
from inv.models import Pelicula

class Cliente(ClaseModelo):

    NAT = 'Natural'
    JUR = 'Jurídica'

    TIPPO_CLIENTE = [
        (NAT,'Natural'),
        (JUR,'Jurídica')
    ]


    nombres = models.CharField('Nombres', max_length=100)
    apellidos = models.CharField('Apeliidos', max_length=100)
    celular = models.CharField('Celular', max_length=20, null=True, blank=True)
    tipo = models.CharField('Tipo', max_length=10, choices=TIPPO_CLIENTE, default=NAT)

    def __str__(self):
        return '{} {}'.format(self.apellidos,self.nombres)

    def save(self):
        self.nombres = self.nombres.upper()
        self.apellidos = self.apellidos.upper()
        super(Cliente,self).save()

    class Meta:
        verbose_name_plural = "Clientes"


class FacturaEnc(ClaseModelo2):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    fecha = models.DateTimeField('Fecha', auto_now_add=True)
    sub_total = models.FloatField(default=0)
    descuento = models.FloatField(default=0)
    total = models.FloatField(default=0)

    def __str__(self):
            return '{}'.format(self.id)

    def save(self):
        self.total = self.sub_total - self.descuento
        super(FacturaEnc,self).save()

    class Meta:
        verbose_name_plural = "Encabezado Facturas"
        verbose_name="Encabezado Factura"
        permissions = [
            ('sup_caja_facturaenc', 'Permiso de supervisor de caja encabezado')
        ]
        
    

class FacturaDet(ClaseModelo2):
    factura = models.ForeignKey(FacturaEnc ,on_delete=models.CASCADE)
    pelicula=models.ForeignKey(Pelicula ,on_delete=models.CASCADE)
    cantidad=models.BigIntegerField(default=0)
    precio=models.FloatField(default=0)
    sub_total=models.FloatField(default=0)
    descuento=models.FloatField(default=0)
    total=models.FloatField(default=0)

    def __str__(self):
        return '{}'.format(self.producto)

    def save(self):
        self.sub_total = float(float(int(self.cantidad)) * float(self.precio))
        self.total = self.sub_total - float(self.descuento)
        super(FacturaDet, self).save()
    
    class Meta:
        verbose_name_plural = "Detalles Facturas"
        verbose_name="Detalle Factura"
        permissions = [
            ('sup_caja_facturadet', 'Permisos de Supervisor de caja detalle')
        ]
        


@receiver(post_save, sender=FacturaDet)
def detalle_fac_guardar(sender, instance, **kwargs):
    factura_id = instance.factura.id
    pelicula_id = instance.pelicula.id


    enc = FacturaEnc.objects.get(pk=factura_id)
    if enc:
        sub_total = FacturaDet.objects \
            .filter(factura=factura_id) \
            .aggregate(sub_total=Sum('sub_total')) \
            .get('sub_total', 0.00)
        descuento = FacturaDet.objects \
            .filter(factura=factura_id) \
            .aggregate(sub_total=Sum('descuento')) \
            .get('descuento', 0.00)

        enc.sub_total = sub_total
        enc.descuento = descuento
        enc.save()

    prod = Pelicula.objects.filter(pk=pelicula_id).first()
    if prod:
        cantidad = int(prod.existencia) - int(instance.cantidad)
        prod.existencia = cantidad
        prod.save()

fac/forms.py
from django import forms

from .models import Cliente


class ClienteForm(forms.ModelForm):

   

    class Meta:
        model = Cliente
        fields=['nombres', 'apellidos', 'celular', 'tipo', 'estado']
        exclude = ['um','fm','uc','fc']
        
    def __init__(self, *args, **kwargs):
        super(ClienteForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

fac/views.py
from django.shortcuts import redirect, render
from django.views import generic
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.http import HttpResponse
from datetime import date, datetime
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth import authenticate


# Create your views here.
from bases.views import Simp
from inv.models import Pelicula

from .models import Cliente, FacturaEnc, FacturaDet
from .forms import ClienteForm
import inv.views as inv

class ClienteView(Simp, generic.ListView):
    
    model = Cliente
    template_name = 'cmp/cliente_list.html'
    context_object_name = 'obj'
    permission_required = 'cmp.view_cliente'


class VistaBaseCreate(SuccessMessageMixin, Simp, generic.CreateView):
    context_object_name = 'obj'
    success_message="Registro Agregado Satisfactoriamente"


    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)

class VistaBaseEdit(SuccessMessageMixin, Simp, generic.UpdateView):
    context_object_name = 'obj'
    success_message="Registro Actualizado Satisfactoriamente"


    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)



class ClienteNew(VistaBaseCreate):
    model = Cliente
    template_name = 'fac/cliente_form.html'
    form_class = ClienteForm
    success_url = reverse_lazy("fac:cliente_list")
    permission_required = 'fac.add_cliente'


class ClienteEdit(VistaBaseEdit):
    model = Cliente
    template_name = 'fac/cliente_form.html'
    form_class = ClienteForm
    success_url = reverse_lazy("fac:cliente_list")
    permission_required = 'fac.change_cliente'




@login_required(login_url="/login/")
@permission_required("fac.change_cliente", login_url="/login/")
def cliente_inactivar(request, id):
    cliente = Cliente.objects.filter(pk=id).first()


    if request.method == 'POST':
        if cliente:

            cliente.estado = not cliente.estado
            cliente.save()
            return HttpResponse("OK")
        return HttpResponse('Fail')
    
    return HttpResponse("Fail")


class FacturaView(Simp, generic.ListView):
    model = FacturaEnc
    template_name = "fac/factura_list.html"
    context_object_name = "obj"
    permission_required = "fac.view_facturaenc"



@login_required(login_url="/login/")
@permission_required("fac.change_facturaenc", login_url="base:simp")
def facturas(request, id=None):
    template_name = "fac/facturas.html"
    
    detalle = {}
    clientes = Cliente.objects.filter(estado=True)

    if request.method=="GET":
        enc = FacturaEnc.objects.filter(pk=id).first()
        
        if not enc:
            print('oli')
            encabezado = {
                "id":0,
                'fecha': datetime.today(),
                "cliente":0,
                "sub_total": 0.00,
                "descuento": 0.00,
                "total": 0.00
            } 
            detalle={}
        else:
            print('hola')
            print(enc.descuento)
            encabezado = {
                "id":enc.id,
                'fecha': enc.fecha,
                "cliente":enc.cliente,
                "sub_total": enc.sub_total,
                "descuento": enc.descuento,
                "total": enc.total
            } 

            detalle=FacturaDet.objects.filter(factura=enc)
    
    
        contexto = {
            "enc": encabezado,
            "det": detalle,
            "clientes": clientes
        }

    if request.method=="POST":
        cliente = request.POST.get("enc_cliente")
        fecha = request.POST.get("fecha")
        cli = Cliente.objects.get(pk=cliente)

        if not id:
            enc = FacturaEnc(
                cliente = cli,
                fecha = fecha
            )

            if enc:
                enc.save()
                id = enc.id
        else:
            enc = FacturaEnc.objects.filter(pk=id).first()

            if enc:
                enc.cliente = cli
                enc.save()
        
        if not id:
            messages.error(request, "No puedo continuar no pude detectar No. de Factura")
            return redirect("fac:factura_list")

        codigo = request.POST.get("codigo")
        cantidad = request.POST.get("cantidad")
        precio = request.POST.get("precio")
        s_total = request.POST.get("sub_total_detalle")
        descuento = request.POST.get("descuento_detalle")
        total = request.POST.get("total_detalle")
        

        prod = Pelicula.objects.get(codigo=codigo)
        det = FacturaDet(
            factura = enc,
            pelicula = prod,
            cantidad = cantidad,
            precio = precio,
            sub_total = s_total,
            descuento = descuento,
            total = total
        )

        if det:
            det.save()

        return redirect("fac:factura_edit", id=id)
    
    return render(request, template_name, contexto)


class PeliculaView(inv.PeliculaView):
    template_name = "fac/buscar_producto.html"
    

def borrar_detalle_factura(request, id):

    template_name = "fac/factura_borrar_detalle.html"

    det = FacturaDet.objects.get(pk=id)

    if request.method == 'GET':

        context = {'det':det}

    if request.method == "POST":
        usr = request.POST.get('usuario')
        password = request.POST.get('password')

        user = authenticate(username=usr, password=password)

        if not user:
            return HttpResponse("Usuario o clave incorrecta")

        if not user.is_active:
            return HttpResponse("Usuario inactivo")

        if user.is_superuser or user.has_perm("fac.sup_caja_facturadet"):
            det.id = None
            det.cantidad = (-1* det.cantidad)
            det.sub_total = (-1* det.sub_total)
            det.descuento = (-1* det.descuento)
            det.total = (-1* det.total)
            det.save()

            return HttpResponse("ok")
            
        return HttpResponse("Usuario no autorizado")
    
    return render(request, template_name, context)

templates/fac/buscar_producto.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="col-xl-12 col-md-12 mb-12">
            <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            Buscar Producto
                        </div>
                        <div class="dropdown-divider"></div>
                        
                        <div class="row">
                                <table
                                id="tblProducto"
                                data-pagination="true"
                                data-search="true"
                                data-show-columns="true"
                                data-show-fullscreen="true"
                                data-locale="es-NI"
                                >
                                <thead>
                                  <th data-sortable="true" data-field="id">Id</th>        
                                  <th data-sortable="true" data-field="codigo">Código</th>
                                  <th data-field="descripcion">Descripción</th>
                                  <th data-field="existencia">Existencia</th>
                                  <th data-field="precio">Precio</th>
                                  <th class="all">Acciones</th>
                                </thead>
                                <tbody>
                                  {% for item in obj %}
                                  <tr>
                                    <td>{{ item.id }}</td>
                                    <td>{{ item.codigo }}</td>
                                    <td>{{item.nombre}}</td>
                                    <td>{{item.existencia}}</td>
                                    <td>{{item.precio}}</td>
                                    <td>
                                        
                                        {% if item.existencia > 0 and item.estado %}
                                            <button class="btn btn-warning btn-circle" id="btnSelect"
                                            onclick="selectPeli({{ item.id }}, '{{ item.codigo }}', '{{ item.nombre }}', {{ item.precio }})"
                                            >
                                                <i class="far fa-hand-pointer"></i>
                                            </button>
                                        {% endif %}
                                            
                                    </td>
                                  </tr>
                                  {% endfor %}
                                </tbody>
                              </table>
                        </div>
                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col">
                                <button type="button" id="btnCancelar" class="btn btn-success">
                                     
                                        Cancelar
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="far fa-calendar-plus fa-2x text-gray-300"></i>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> 



{% block js %}
    
    <script>
        $(function(){
            
            $("#btnCancelar").click(function(e){
                e.preventDefault();
                cerrar_modal();
            });
        
        });

        $("#tblProducto").bootstrapTable();

        function selectPeli(id,codigo,nombre,precio){
            $("#codigo").val(codigo);
            $("#descripcion").val(nombre);
            $("#precio").val(precio);
            $("#btnCancelar").click();
            $("#codigo").select();
            $("#codigo").focus();
        }

    </script>

{% endblock js %}
    

templates/fac/cliente_form.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">


        
        {% if obj %}
        <form action="{% url 'fac:cliente_edit' obj.pk %}" role="form" method="post" class="form-inline">
        
        {% else %}
        <form action="{% url 'fac:cliente_new' %}" role="form" method="post" class="form-inline">

        {% endif %}
            
            {% csrf_token %}
            <div class="col-xl-12 col-md-12 mb-12">
                
                {% if obj %}
                <div class="card border-left-warning shadow h-100 py-2">
                {% else %}
                <div class="card border-left-success shadow h-100 py-2">

                {% endif %}
                    
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                
                                {% if obj %}
                                    Editar
                                {% else %}
                                    Nuevo
                                {% endif %}
                                    Cliente
                                </div>
                                <div class="dropdwon-divider"></div>
                                <div class="row my-3">
                                    {{ form.as_p }}
                                </div>
                                <div class="dropdwon-divider"></div>
                                <div class="row">
                                    <div class="col">
                                        <button type="submit" class="btn btn-success"><span class="fa fa-save"></span> Guardar</button>
                                       
                                        <button class="btn btn-danger" onclick="return cerrar_modal()">Cancelar</button>
                                    </div>
                                </div>
                            </div>
            
                        </div>
                    </div>
                </div>
            </div>
        </form>

    </div>
</div>  
    

templates/fac/cliente_list.html
{% extends 'base/base.html' %}



{% block content %}
    
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Listado de Clientes</h6>
      <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
          <div class="dropdown-header">Acciones</div>
          <a class="dropdown-item" href="#" onclick="return abrir_modal('{% url 'fac:cliente_new' %}');"><i class="far fa-calendar-plus"></i> Nuevo</a>
          
        </div>
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
     
     {% if not obj %}
         <div class="alert alert-info">No hay clientes que mostrar</div>
     {% endif %}

     <div class="buttons-toolbar">
        <a class="dropdown-item" href="#" onclick="return abrir_modal('{% url 'fac:cliente_new' %}');"><i class="far fa-calendar-plus"></i> Nuevo</a>
     </div>
     <table id="table" data-toggle="table" data-pagination="true"
     data-search="true" data-show-columns="true" data-show-toggle="true"
     data-show-fullscreen="true" data-toolbar=".buttons-toolbar" data-locale="es-CL">
         <thead>
             <th data-field="id" data-sortable="true">Id</th>
             <th data-sortable="true" data-field="Nombres">Nombres</th>
             <th data-sortable="true" data-field="Apellidos">Apellidos</th>
             <th data-field="Tipo">Tipo</th>           
             <th data-field="Teléfono">Teléfono</th>
             <th data-field="Estado">Estado</th>
             <th class="all">Acciones</th>
         </thead>
         <tbody>
             
             {% for item in obj %}
                 <tr>
                     <td>{{ item.id }}</td>
                     <td>{{ item.nombres }}</td>
                     <td>{{ item.apellidos }}</td>
                     <td>{{ item.tipo }}</td>
                     <td>{{ item.celular }}</td>
                     <td>{# item.estado|yesno:"Activo,Inactivo" #}
                         <div onclick="inactivar({{ item.id }})">
                             {% if item.estado %}
                                <i class="far fa-thumbs-up text-primary"></i>
                             {% else %}
                                <i class="far fa-thumbs-down text-danger"></i>
                             {% endif %}
                         </div>
                     </td>

                     <td>
                         <a href="#"  class="btn btn-warning btn-circle" onclick="return abrir_modal('{% url 'fac:cliente_edit' item.id %}')" role="button"><i class="far fa-edit"></i></a>
                     </td>
                 </tr>
             {% endfor %}
                 
         </tbody>
     </table>

    </div>
  </div>

{% endblock content %}
    


{% block js %}
    

<script>

    function inactivar(id) {
        var data = {id:id};
        data = JSON.stringify(data);
        var token = '{{ csrf_token }}';
        // alert(token);
        // alert(id);
        
      

        $.ajax({
            headers     :{"X-CSRFToken": token},
            type        :"POST",
            url         :"/fac/cliente/estado/"+id,
            data        :data,
            success     :function(response){
                if(response==="OK"){
                    location.reload(true);
                }
                else{
                    mensaje("Error intentado cambiar estado del cliente");
                }
            },
            error       : function(jqXHR,textStatus,errorThrow){
                console.log(textStatus, errorThrow);
                mensaje(errorThrow, 'red');
                cerrar_modal();
            }
        });
    }


    // $(document).ready(function(){
    //     $('.table').DataTable();
    // });
</script>


{% endblock js %}
    

templates/fac/factura_borrar_detalle.html
<label class="text-danger">¿Anular Producto <b>{{det.pelicula.nombre}}</b> de factura <b>{{det.factura.id}}</b>?</label>
<div>
    <div class="form-group">
        <label class="control-label">Usuario</label>
        <input type="text" id="usuario" class="form-control" required>
    </div>
    <div class="form-group">
        <label class="control-label">Contraseña</label>
        <input type="password" id="password" class="form-control" required>
    </div>
</div>

templates/fac/factura_list.html
{% extends 'base/base.html' %}



{% block content %}
    
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Listado de Facturas</h6>
      <!-- <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
          <div class="dropdown-header">Acciones</div>
          <a class="dropdown-item" href="#" onclick="return abrir_modal('{# url 'fac:cliente_new' #}');"><i class="far fa-calendar-plus"></i> Nuevo</a>
          
        </div>
      </div> -->
    </div>
    <!-- Card Body -->
    <div class="card-body">
      <div class="row">
        <div class="col-md-4">
          <input type="text" class="form-class" name="f1" id="f1" readonly>
        </div>
        <div class="col-md-4">
          <input type="text" class="form-class" name="f2" id="f2" readonly>
        </div>
        <div class="col-md-4">
          <button class="btn btn-warning" type="button" id="btnPrint">Imprimir</button>
        </div>
      </div>
      <hr>
     
     {% if not obj %}
         <div class="alert alert-info">No hay facturas que mostrar</div>
     {% endif %}

     <div class="buttons-toolbar">
        <a class="btn btn-success" href="{% url 'fac:factura_new' %}" ><i class="far fa-calendar-plus"></i> Nuevo</a>
     </div>
     <table id="table" data-toggle="table" data-pagination="true"
     data-search="true" data-show-columns="true" data-show-toggle="true"
     data-show-fullscreen="true" data-toolbar=".buttons-toolbar" data-locale="es-CL">
         <thead>
             <th data-field="id" data-sortable="true">No.</th>
             <th data-sortable="true" data-field="Nombres">Cliente</th>
             <th data-sortable="true" data-field="Apellidos">Total</th>
             <th data-field="Estado">Estado</th>
             <th class="all">Acciones</th>
         </thead>
         <tbody>
             
             {% for item in obj %}
                 <tr>
                     <td>{{ item.id }}</td>
                     <td>{{ item.cliente }}</td>
                     <td>{{ item.total }}</td>
                     <td>{{ item.estado|yesno:"Activo,Inactivo" }}
                         
                     </td>

                     <td>
                         <a href="{% url 'fac:factura_edit' item.id %}"  class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
                     </td>
                 </tr>
             {% endfor %}
                 
         </tbody>
     </table>

    </div>
  </div>

{% endblock content %}
    


{% block js %}
    

<script>

$(function(){
  $('#f1, #f2').datetimepicker({
      format: 'Y-m-d',
      timepicker: false
  });
  $("#btnPrint").click(function(e){
    e.preventDefault();
    var f1,f2;
    f1 = $("#f1").val();
    f2 = $("#f2").val();
    if(f1=="" || f1==null){
      f1="2019-06-01";
    }
    if(f2=="" || f2==null){
      var d = new Date();
      var f2 = d.getFullYear() + "-" + (d.getMonth()+1) + "-" + d.getDate();
    }
    
    var url = "imprimir-todas/" + f1 + "/" + f2;

    // alert(url)

    window.open(url,'facturas');
    
  });
});
   
</script>


{% endblock js %}
    

templates/fac/factura_one.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Listado de Compras</title>
    <link rel="stylesheet" href="{% static 'css/recibo.css' %}">
    <style type="text/css">
        @page {
             width: 58mm; 
            size: auto;   
            margin: 0mm;
            }
    </style>
</head>
<body onload="window.print()" class="receipt">
    <div class="col-md-1 col-sm-1 col-xs-1 col-xl-1">
        <center>
            <b class="text-center">Tienda de pelis</b><br> 
            <small>Direccion</small><br>
            <small>FACTURA No. {{enc.factura}}</small><br>
        </center>
        <small>
            <br>
            <b>Factura No.:</b>&nbsp;&nbsp;{{enc.id}}&nbsp;&nbsp;
            <b>Fecha Fact:</b>&nbsp;&nbsp;{{enc.fecha}}&nbsp;&nbsp; <br>
            <b>Cliente:</b>&nbsp;&nbsp;{{enc.cliente.id}}&nbsp;&nbsp;- {{enc.cliente}}<br>
            <br><br>
        </small>
        <table class="table table-condensed table-sm" width="60%">
            <thead>
                <th>Código</th>
                <th  align='right'>Cant.</th>
                <th  align='right'>P. Unit.</th>
                <th  align='right'>Sub Total</th>
                <th  align='right'>Descuento</th>
                <th  align='right'>Total</th>
            </thead>
            <tbody>
                {% for obj in detalle %}
                <tr>
                    <td>{{obj.pelicula.id}}</td>
                    <td>{{obj.cantidad}}</td>
                    <td>{{obj.precio}}</td>
                    <td>{{obj.sub_total}}</td>
                    <td>{{obj.descuento}}</td>
                    <td>{{obj.total}}</td>
                </tr>
                <tr>
                    <td colspan="5">{{obj.pelicula}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="col-xs-1"></div>
        <div class="col-xs-11">
            <div class="pull-right">
            <table class="table-responsive dt-responsive nowrap">
                <thead>
                    <th colspan=2>Totales</th>
                </thead>
                <tbody>
                    <tr>
                        <td>Sub Total:</td> <td align='right'>{{enc.sub_total}}</td>
                    </tr>
                    <tr>
                        <td>Iva:</td> <td align='right'>{{enc.descuento}}</td>
                    </tr>
                    <tr>
                        <td>Total:</td> <td align='right'><b>{{enc.total}}</b></td>
                    </tr>
                </tbody>
            </table>
            </div>
        </div>
        <div class="row">
        <small class="pie">
            <br><br>
            <center>
                Creada por:  {{enc.uc}} - Fecha:  {{enc.fc}}
                <br>
                <i>&copy; &reg; <b>Luis Felipe Echeverry</b><br> - lfelipe.desarrollador@gmail.com</i> 
            </center>
        </small>
        </div>
    </div>
</body>
</html>